server.port=8080

# SQL Server - Windows Authentication
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=expense_tracker;encrypt=true;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JWT
jwt.secret=dharmik_expense_tracker_super_secret_key_2024_spring_boot
jwt.expiration=86400000
